### PR TITLE
Cloned and branched repository + Add to particpant list

### PR DESCRIPTION
**Pull request by sriram010689**
This is related to issue #

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@sriram010689 Thanks for your pull-request. There are conflicts because an other participant edited the document in the mean time. Can you click on "Resolve conflicts" or follow the command line instructions to update your document?

**Comment by niccokunzmann** [comment]
@irinazz When you [accept the invitation](https://github.com/KDD-OpenSource/geox-young-academy/invitations), I think you should be able to merge this pull-request once the conflict is resolved.

**Comment by sriram010689** [comment]
@niccokunzmann : Hello Nicco. I am trying out Git for the first time. Probably, messed up a little bit. Let me see what I can do. Thanks for your consideration.

**Comment by niccokunzmann** [comment]
You did not mess up. I guess, you added your name below my name. Git does not understand which line comes first: yours or the line from #2. Everyone would get the same error and it is normal to have that.

**Comment by sriram010689** [comment]
Alrighty. Can I just delete this pull request? I made another one. Also, I will try to delete that test-branch I created. Thank you, this is fun :+1:

**Comment by niccokunzmann** [comment]
You can close it. If you like to delete your branch, go to your repo, click on "code" then on "branches" and then, I do not know.

**Comment by niccokunzmann** [comment]
Please mention why you close it: #6.

**Comment by sriram010689** [comment]
Pull-request closed because of conflicts in file changes.

**Pull request closed without merging**
